### ISSUE TITLE
What is the approach?

### ISSUE THREAD

**Issue by bonndan** [nicmart/PhpGenerics#2]
The author of https://github.com/ircmaxell/PhpGenerics recommends not to use his library. In how far is your approach different?

**Comment by nicmart** [comment]
The main differences are
1. Generated parametrised types code is persisted in a cache folder, so it is only generated once
2. There is no call-site code rewriting
3. Multiple type parameters are allowed
4. Generic names and parametrised names are valid class/interface names, so all the code is valid PHP and IDE-friendly (that's why I chose `«»` as default type parameters brackets and `·` as type parameters separator, all of them valid PHP type identifiers)

So if you have a generic class like `Some«T»` (see examples directory), that is a valid php class, with a valid name, and inside the class `T` is a valid (empty) interface. The first time a client calls something like `new Some«stdClass»`, a copy of `Some«T»` will be generated, in which all usages of `T` will be replaced with `stdClass`. On the following usages, the autoloader will retrieve the already-compiled `Some«stdClass»`.

The main point is that there is no overhead at runtime for code generation. Of course you can pay the cost of loading more classes and interfaces.

The library is still experimental and on heavy development, but the functionality is already in place. You can try what is happening running the tests and checking the content of the "cache/generics" folder.

**Comment by bonndan** [comment]
Cool. I'm curious to see where this leads to. Refactoring in IDEs might become a bit tricky, but having typed collections is very interesting. :+1:
